services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/code
      - pip:/usr/local/lib/python3.11/site-packages
    command: devel_web
    ports:
      - "8000:8000"
    depends_on:
      - email
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=settings.docker_devel
  frontend:
    build:
      context: ./frontend
    environment:
      - NODE_ENV=development
    command: npm start
    volumes:
      - ./frontend:/code
      - node_modules:/code/node_modules
    ports:
      - "3000:3000"
  email:
    image: python:3.11
    command: sh -c "pip install aiosmtpd -q && python -m aiosmtpd -n -l 0.0.0.0:1025"
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  pip:
  node_modules:
