version: '3.5'

services:
  backend:
    volumes:
      - ./backend:/code
      - pip:/usr/local/lib/python3.11/site-packages
    command: devel_web
    ports:
      - "8000:8000"
    depends_on:
      - email
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=settings.docker_devel
  frontend:
    environment:
      - NODE_ENV=development
    command: npm start
    volumes:
      - ./frontend:/code
      - node_modules:/code/node_modules
    ports:
      - "3000:3000"
  email:
    image: python:3.11
    command: sh -c "pip install aiosmtpd -q && python -m aiosmtpd -n -l 0.0.0.0:1025"

volumes:
  pip:
  node_modules:
