# Generated by Django 2.0.6 on 2018-09-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("games", "0003_auto_20180921_1913")]

    operations = [
        migrations.AlterField(
            model_name="gamesession",
            name="spots",
            field=models.PositiveIntegerField(default=1, verbose_name="Number of spots"),
        )
    ]
