# Generated by Django 2.0.6 on 2018-10-20 14:13

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [("games", "0006_auto_20181005_0837")]

    operations = [
        migrations.AlterModelManagers(name="gamesession", managers=[("games", django.db.models.manager.Manager())]),
        migrations.AddField(
            model_name="gamesession", name="active", field=models.BooleanField(default=False, verbose_name="Active")
        ),
    ]
