# Generated by Django 2.0.9 on 2019-02-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("games", "0011_auto_20181223_1613")]

    operations = [
        migrations.AddField(
            model_name="adventure",
            name="tier",
            field=models.CharField(
                blank=True,
                choices=[("tier1", "Trier 1"), ("tier2", "Trier 2"), ("tier3", "Trier 3"), ("tier4", "Trier 4")],
                max_length=6,
                null=True,
                verbose_name="Tier",
            ),
        )
    ]
