# Generated by Django 2.0.9 on 2019-08-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("games", "0012_adventure_tier")]

    operations = [
        migrations.AlterField(
            model_name="adventure",
            name="tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tier1", "Tier 1 (Level 1-4)"),
                    ("tier2", "Tier 2 (Level 5-10)"),
                    ("tier3", "Tier 3 (Level 11-16)"),
                    ("tier4", "Tier 4 (Level 17-20)"),
                ],
                max_length=6,
                null=True,
                verbose_name="Tier",
            ),
        )
    ]
