# Generated by Django 2.2.9 on 2020-02-01 20:55

from django.db import migrations, models

from ..constants import ONLINE_TABLE_NAME


def add_online_table(apps, schema_editor):
    Table = apps.get_model("games", "Table")

    try:
        Table.objects.get(name=ONLINE_TABLE_NAME)
    except Table.DoesNotExist:
        Table.objects.create(
            name=ONLINE_TABLE_NAME,
            max_spots=7,
        )


class Migration(migrations.Migration):

    dependencies = [("games", "0014_table_extra_notes")]

    operations = [migrations.RunPython(add_online_table, migrations.RunPython.noop)]
