# Generated by Django 5.2 on 2026-03-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_online_table_adding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesessionplayersignup',
            name='reported',
            field=models.BooleanField(default=None, null=True, verbose_name='Reported'),
        ),
    ]
