ADVENTURE_TYPE_EN = 1
ADVENTURE_TYPE_EP = 2
ADVENTURE_TYPE_EX = 3
ADVENTURE_TYPE_HC = 4
ADVENTURE_TYPE_IA = 5
ADVENTURE_TYPE_LE = 6
ADVENTURE_TYPE_CCC = 7
ADVENTURE_TYPE_AO = 8
ADVENTURE_TYPE_OTHER = 9
ADVENTURE_TYPE_AL = 10

ADVENTURE_TIER1 = "tier1"
ADVENTURE_TIER2 = "tier2"
ADVENTURE_TIER3 = "tier3"
ADVENTURE_TIER4 = "tier4"

MINIMUM_PLAYERS_COUNT = 3

ONLINE_TABLE_NAME = "Online"

FUTURE_TABLES_ADDED_AMOUNT = 30
AFTER_HOW_MANY_DAYS_ADD_TABLES = 28
