# Generated by Django 2.0.6 on 2018-07-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("profiles", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="nickname",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Nickname"),
        )
    ]
