# Generated by Django 2.0.6 on 2018-08-25 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("profiles", "0003_auto_20180824_1909")]

    operations = [
        migrations.AlterField(
            model_name="playercharacter",
            name="faction",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="profiles.CharacterFaction"
            ),
        )
    ]
