# Generated by Django 2.0.9 on 2019-07-18 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("profiles", "0009_auto_20181220_1636")]

    operations = [
        migrations.RemoveField(model_name="dmnote", name="dm"),
        migrations.RemoveField(model_name="dmnote", name="player"),
        migrations.DeleteModel(name="DMNote"),
    ]
