# Generated by Django 2.0.9 on 2019-08-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("profiles", "0010_auto_20190718_2034")]

    operations = [
        migrations.AddField(model_name="playercharacter", name="dead", field=models.BooleanField(default=False))
    ]
