name: Deploy Backend

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - backend/**

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          username: ${{ secrets.USERNAME }}
          script: ${{ secrets.BACKEND_DEPLOY_DIR }}/deploy.sh
